name: scoreX
main: com.scorex.ScoreX
version: 1.0.0
author: MoonIsaa
description: A cool multi-language scoreboard plugin for Spigot 1.16.5+
api-version: 1.16

softdepend:
  - PlaceholderAPI
  - Vault
  - LuckPerms
  - WorldGuard
  - CMI

commands:
  scorex:
    description: Main command for scoreX plugin
    usage: /<command> reload
    permission: scorex.admin
    permission-message: You do not have permission to use this command.
